### ISSUE TITLE
質問。。32pixelじゃなくて、128X128pixelのイメージを利用して学習したいのです。

### ISSUE THREAD

**Issue by seossine** [daiz713/tfPhotoClassifier#4]
32pixelじゃなくて、128X128pixelのイメージを利用して学習したいのです。
ソースの中で
size = {
    # feed-cropped-image size
    #32 x 32
    'width': 32,
    'height': 32,
    # inside 24 x 24 in 32 x 32
    'input_width': 24,
    'input_height': 24,
    # RGB
    'depth': 3,
    # ラベルの桁数
    'label': 1
}

を
size = {
    # feed-cropped-image size
    #128 x 128
    'width': 128,
    'height': 128,
    # inside 96 x 96 in 128 x 128
    'input_width': 96,
    'input_height': 96,
    # RGB
    'depth': 3,
    # ラベルの桁数
    'label': 1
}

に変更すれば、学習に問題ないでしょうか？

**Comment by daiiz** [comment]
はい、OKです！

**Comment by seossine** [comment]
ありがとうございます。
